//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Wednesday, 2 January 2019 3:39 PM
//  T4 template:  TechChallengeDb.tt
//  How to trigger: Got Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
// </auto-generated>
//------------------------------------------------------------------------------
using TechChallenge.Business.Common.Entities;
using System.Data.Entity;

namespace TechChallenge.Data
{
    public class TechChallengeDb : DbContext
    {
        public DbSet<Bet> Bets { get; set; }

        public DbSet<Customer> Customers { get; set; }

        public DbSet<Horse> Horses { get; set; }

        public DbSet<Race> Races { get; set; }
    }
}
