//------------------------------------------------------------------------------
// <auto-generated>
//  Last update:  Thursday, 3 January 2019 5:51 AM
//  T4 template:  TechChallengeDb.tt
//  How to trigger: Goto Properties -> Custom Tool -> rename from TextTemplatingFileGeneratorr to TextTemplatingFileGenerator
//  How to disable: Rename from TextTemplatingFileGenerator back to TextTemplatingFileGeneratorr
// </auto-generated>
//------------------------------------------------------------------------------
using TechChallenge.Business.Common.Entities;
using TechChallenge.Contracts.Infrastructure;
using System.Data.Entity;

namespace TechChallenge.Data
{
    public class TechChallengeDb : DbContext
    {
        public TechChallengeDb()
            : base(ConnectionStrings.TechChallengeKey)
        {
        }

        public DbSet<Bet> Bets { get; set; }

        public DbSet<Customer> Customers { get; set; }

        public DbSet<Horse> Horses { get; set; }

        public DbSet<Race> Races { get; set; }
    }
}
