// <auto-generated />
namespace TechChallenge.DataMigration.TechChallengeDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedBets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedBets));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071138175_SeedBets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
