// <auto-generated />
namespace TechChallenge.DataMigration.TechChallengeDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedHorses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedHorses));
        
        string IMigrationMetadata.Id
        {
            get { return "201912071137455_SeedHorses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
