//------------------------------------------------------------------------------
// <auto-generated>
//  Date updated:  Tuesday, 1 January 2019 7:48 PM
//  Template:  EntitySortableFieldEnums.tt
//  * Enum members are arranged from top to bottom, the same order it was declared.
//  * Or use SortOrder attribute into your property.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TechChallenge.Business.Common.Entities
{
    public enum eHorse
    {
        Name,
        Odds
    }

    public enum eRace
    {
        Name,
        Status,
        Start
    }
}
